### ISSUE TITLE
100%+ CPU Usage

### ISSUE THREAD

**Issue by Bunn** [crossroadlabs/Express#15]
When running the [Getting Started](https://github.com/crossroadlabs/Express#getting-started) guide the CPU usage stays constant on 100%+ CPU usage

![cpu](https://cloud.githubusercontent.com/assets/782316/13512771/72b2e4f2-e17b-11e5-8c41-a5214c510e24.png)

**Comment by dileping** [comment]
Hi @Bunn,

thanks for reporting the issue. Could you, please, provide some more details. Like what command exactly have you executed, etc. This way I could help you better.

Thanks,
Daniel

**Comment by Bunn** [comment]
Hi, @dileping 
I just did the step by step instructions on the Getting Started guide.

Right after running `swift-express run` the CPU spikes to 100%+ and stays there.

```
swift-express run
Building HelloExpress in Debug mode...
Running HelloExpress...
Express was successfully launched on port 9999
```

**Comment by dileping** [comment]
@Bunn ,

thanks for reporting the details! I can reproduce it now. We will fix it as soon as possible and let you know once done.

**Comment by dileping** [comment]
@Bunn ,

thanks again for reporting the bug. It was very helpful and now it's fixed in the new major release of [Express Command Line](https://github.com/crossroadlabs/ExpressCommandLine): **0.2.0**.

To update to the new version, please, run:

``` sh
brew update
brew upgrade swift-express
```

Keep in mind, that the API of command line has evolved and is slightly different now. Consider taking a look at original project page documentation: [Express Command Line](https://github.com/crossroadlabs/ExpressCommandLine).

Will be very glad to hear some feedback on the new version.

Regards,
Daniel

**Comment by Bunn** [comment]
CPU Usage is now at 0.3% :)

**Comment by dileping** [comment]
@Bunn  Great! Thanks for reporting back!
